#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use CommissionTask\Service\CurrencyService;
use CommissionTask\Service\Importers\CsvRowsReader;
use CommissionTask\Service\UserBalanceStore;
use Monolog\Handler\StreamHandler;
use Monolog\Logger;
use Symfony\Component\Console\Application;
use CommissionTask\Console\Command\CalculateCommission;
use Symfony\Component\Dotenv\Dotenv;

$dotenv = new Dotenv();
$dotenv->usePutenv(true)->bootEnv(__DIR__.'/.env');

$application = new Application();
$log = new Logger('default');
$log->pushHandler(new StreamHandler('var/log/' . getenv('APP_ENV') . '.log'));

$csvRowsReader = new CsvRowsReader();

$application->add(new CalculateCommission($csvRowsReader, $log));

$application->run();
